import { buildEnv } from "@cap/env";

const en = {
	"password.title": "Protected Video",
	"password.description":
		"This video is password protected. Please enter the password to continue watching.",
	"password.label": "Password",
	"password.placeholder": "Enter password",
	"password.verifying": "Verifying...",
	"password.submit": "Access Video",

	"auth.back": "Back",
	"auth.signInTitle": "Sign in to comment",
	"auth.emailSentTitle": "Email sent",
	"auth.signInSubtitle": "Join the conversation.",
	"auth.emailSentSubtitle": "We sent a 6-digit code to your email.",
	"auth.continueWithEmail": "Continue with Email",
	"auth.emailSentInbox": "Email sent to your inbox",
	"auth.emailSentTerminal": "Email sent to your terminal",
	"auth.emailSentToast": "Email sent - check your inbox!",
	"auth.emailErrorToast": "Error sending email - try again?",
	"auth.or": "OR",
	"auth.loginWithGoogle": "Login with Google",
	"auth.termsText":
		"By entering your email, you acknowledge that you have both read and agree to Cap's",
	"auth.termsOfService": "Terms of Service",
	"auth.privacyPolicy": "Privacy Policy",

	"header.notShared": "Not shared",
	"header.shared": "Shared",
	"header.sharedWithYou": "Shared with you",
	"header.linkLimitedFree":
		"Shareable links are limited to 5 mins on the free plan.",
	"header.upgradePro": "Upgrade To Cap Pro",
	"header.titleUpdated": "Video title updated",
	"header.titleUpdateFailed": "Failed to update title - please try again.",
	"header.connectCustomDomain": "Connect a custom domain",
	"header.goTo": "Go to",
	"header.dashboard": "Dashboard",
	"header.viewAnalytics": "View analytics",

	"sidebar.comments": "Comments",
	"sidebar.summary": "Summary",
	"sidebar.transcript": "Transcript",

	"summary.title": "Summary",
	"summary.generatedBy": "Generated by AI using Mistral AI",
	"summary.chapters": "Chapters",
	"summary.unlockAi": "Unlock Cap AI",
	"summary.unlockAiDescription":
		"Upgrade to Cap Pro to access AI-powered features including automatic titles, video summaries, and intelligent chapter generation.",
	"summary.upgradePro": "Upgrade to Cap Pro",
	"summary.aiFailed": "AI generation failed",
	"summary.aiSkipped": "AI generation skipped",
	"summary.noSummary": "No summary available",
	"summary.aiFailedDescription":
		"There was an error generating the AI summary.",
	"summary.aiSkippedDescription":
		"The video was too short or had no speech detected.",
	"summary.noSummaryDescription":
		"AI summary has not been generated for this video yet.",
	"summary.retrying": "Retrying...",
	"summary.retryGeneration": "Retry AI Generation",

	"transcript.inProgress": "Transcription in progress...",
	"transcript.noAudio": "No audio track detected",
	"transcript.noAudioDescription":
		"This video doesn't contain audio for transcription",
	"transcript.disabled": "Transcription disabled",
	"transcript.disabledDescription":
		"Transcription has been disabled for this video",
	"transcript.notAvailable": "Transcript not available",
	"transcript.noTranscript": "No transcript available",
	"transcript.retrying": "Retrying...",
	"transcript.retryTranscription": "Retry Transcription",
	"transcript.copyTranscript": "Copy Transcript",
	"transcript.copied": "Copied",
	"transcript.download": "Download",
	"transcript.downloaded": "Downloaded",
	"transcript.translating": "Translating...",
	"transcript.original": "Original",
	"transcript.translatingOverlay": "Translating transcript...",
	"transcript.cancel": "Cancel",
	"transcript.save": "Save",
	"transcript.editPlaceholder": "Edit transcript text...",

	"activity.disabled": "Disabled",
	"activity.noComments": "No comments yet",
	"activity.commentsDisabledDescription":
		"Comments are disabled for this video",
	"activity.firstComment": "Be the first to share your thoughts!",

	"toolbar.addComment": "Add a comment",
	"toolbar.comment": "Comment",
	"toolbar.cancel": "Cancel",

	"share.recordedWith": "Recorded with",
	"share.videoPrivate": "This video is private",
	"share.signInToManage": "sign in",
	"share.signInToManageDescription":
		"If you own this video, please {link} to manage sharing.",
	"share.requiresSignIn": "This video requires sign-in",
	"share.emailRestrictionDescription":
		"The owner of this video has restricted access. Please {link} with an authorized email address to view.",
	"share.accessRestricted": "Access restricted",
	"share.emailDeniedDescription":
		"Your email address does not meet the requirements set by the video owner.",

	"meta.titleSuffix": "oaris",
	"meta.watchDescription": "Watch this video on oaris",
} as const;

const de: Record<keyof typeof en, string> = {
	"password.title": "Geschütztes Video",
	"password.description":
		"Dieses Video ist passwortgeschützt. Bitte geben Sie das Passwort ein, um fortzufahren.",
	"password.label": "Passwort",
	"password.placeholder": "Passwort eingeben",
	"password.verifying": "Wird überprüft...",
	"password.submit": "Video ansehen",

	"auth.back": "Zurück",
	"auth.signInTitle": "Anmelden zum Kommentieren",
	"auth.emailSentTitle": "E-Mail gesendet",
	"auth.signInSubtitle": "Nehmen Sie an der Unterhaltung teil.",
	"auth.emailSentSubtitle":
		"Wir haben einen 6-stelligen Code an Ihre E-Mail gesendet.",
	"auth.continueWithEmail": "Weiter mit E-Mail",
	"auth.emailSentInbox": "E-Mail an Ihren Posteingang gesendet",
	"auth.emailSentTerminal": "E-Mail an Ihr Terminal gesendet",
	"auth.emailSentToast": "E-Mail gesendet – prüfen Sie Ihren Posteingang!",
	"auth.emailErrorToast": "Fehler beim Senden der E-Mail – erneut versuchen?",
	"auth.or": "ODER",
	"auth.loginWithGoogle": "Mit Google anmelden",
	"auth.termsText":
		"Mit der Eingabe Ihrer E-Mail bestätigen Sie, dass Sie die folgenden Dokumente gelesen haben und ihnen zustimmen:",
	"auth.termsOfService": "Nutzungsbedingungen",
	"auth.privacyPolicy": "Datenschutzrichtlinie",

	"header.notShared": "Nicht geteilt",
	"header.shared": "Geteilt",
	"header.sharedWithYou": "Mit Ihnen geteilt",
	"header.linkLimitedFree":
		"Teilbare Links sind im kostenlosen Plan auf 5 Minuten begrenzt.",
	"header.upgradePro": "Auf Cap Pro upgraden",
	"header.titleUpdated": "Videotitel aktualisiert",
	"header.titleUpdateFailed":
		"Titel konnte nicht aktualisiert werden – bitte erneut versuchen.",
	"header.connectCustomDomain": "Eigene Domain verbinden",
	"header.goTo": "Zum",
	"header.dashboard": "Dashboard",
	"header.viewAnalytics": "Analysen anzeigen",

	"sidebar.comments": "Kommentare",
	"sidebar.summary": "Zusammenfassung",
	"sidebar.transcript": "Transkript",

	"summary.title": "Zusammenfassung",
	"summary.generatedBy": "Erstellt mit KI von Mistral AI",
	"summary.chapters": "Kapitel",
	"summary.unlockAi": "Cap KI freischalten",
	"summary.unlockAiDescription":
		"Upgraden Sie auf Cap Pro, um KI-Funktionen wie automatische Titel, Videozusammenfassungen und intelligente Kapitelgenerierung zu nutzen.",
	"summary.upgradePro": "Auf Cap Pro upgraden",
	"summary.aiFailed": "KI-Generierung fehlgeschlagen",
	"summary.aiSkipped": "KI-Generierung übersprungen",
	"summary.noSummary": "Keine Zusammenfassung verfügbar",
	"summary.aiFailedDescription":
		"Beim Generieren der KI-Zusammenfassung ist ein Fehler aufgetreten.",
	"summary.aiSkippedDescription":
		"Das Video war zu kurz oder es wurde keine Sprache erkannt.",
	"summary.noSummaryDescription":
		"Für dieses Video wurde noch keine KI-Zusammenfassung erstellt.",
	"summary.retrying": "Wird wiederholt...",
	"summary.retryGeneration": "KI-Generierung wiederholen",

	"transcript.inProgress": "Transkription läuft...",
	"transcript.noAudio": "Keine Audiospur erkannt",
	"transcript.noAudioDescription":
		"Dieses Video enthält kein Audio für die Transkription",
	"transcript.disabled": "Transkription deaktiviert",
	"transcript.disabledDescription":
		"Die Transkription wurde für dieses Video deaktiviert",
	"transcript.notAvailable": "Transkript nicht verfügbar",
	"transcript.noTranscript": "Kein Transkript verfügbar",
	"transcript.retrying": "Wird wiederholt...",
	"transcript.retryTranscription": "Transkription wiederholen",
	"transcript.copyTranscript": "Transkript kopieren",
	"transcript.copied": "Kopiert",
	"transcript.download": "Herunterladen",
	"transcript.downloaded": "Heruntergeladen",
	"transcript.translating": "Wird übersetzt...",
	"transcript.original": "Original",
	"transcript.translatingOverlay": "Transkript wird übersetzt...",
	"transcript.cancel": "Abbrechen",
	"transcript.save": "Speichern",
	"transcript.editPlaceholder": "Transkripttext bearbeiten...",

	"activity.disabled": "Deaktiviert",
	"activity.noComments": "Noch keine Kommentare",
	"activity.commentsDisabledDescription":
		"Kommentare sind für dieses Video deaktiviert",
	"activity.firstComment": "Teilen Sie als Erstes Ihre Gedanken!",

	"toolbar.addComment": "Kommentar hinzufügen",
	"toolbar.comment": "Kommentieren",
	"toolbar.cancel": "Abbrechen",

	"share.recordedWith": "Aufgenommen mit",
	"share.videoPrivate": "Dieses Video ist privat",
	"share.signInToManage": "anmelden",
	"share.signInToManageDescription":
		"Wenn Sie dieses Video besitzen, {link} Sie sich bitte an, um die Freigabe zu verwalten.",
	"share.requiresSignIn": "Für dieses Video ist eine Anmeldung erforderlich",
	"share.emailRestrictionDescription":
		"Der Eigentümer dieses Videos hat den Zugang eingeschränkt. Bitte {link} Sie sich mit einer autorisierten E-Mail-Adresse an.",
	"share.accessRestricted": "Zugang eingeschränkt",
	"share.emailDeniedDescription":
		"Ihre E-Mail-Adresse erfüllt nicht die Anforderungen des Video-Eigentümers.",

	"meta.titleSuffix": "oaris",
	"meta.watchDescription": "Dieses Video auf oaris ansehen",
};

type TranslationKey = keyof typeof en;

const dictionaries: Record<string, Record<TranslationKey, string>> = {
	en,
	de,
};

function getDictionary(): Record<TranslationKey, string> {
	const lang = buildEnv.NEXT_PUBLIC_UI_LANGUAGE || "en";
	return dictionaries[lang] || en;
}

export function t(key: TranslationKey): string {
	return getDictionary()[key];
}

export function tParam(
	key: TranslationKey,
	params: Record<string, string | number>,
): string {
	let result = getDictionary()[key];
	for (const [param, value] of Object.entries(params)) {
		result = result.replace(`{${param}}`, String(value));
	}
	return result;
}

export function getUiLanguage(): string {
	return buildEnv.NEXT_PUBLIC_UI_LANGUAGE || "en";
}
