name: "CI"
on:
  push:
    branches:
      - main
      - oaris/deploy
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  typecheck:
    name: Typecheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup-js

      - run: pnpm web exec next typegen

      - name: Typecheck
        run: pnpm typecheck

  format-biome:
    name: Format (Biome)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: 2.2.0

      - name: Run Biome
        run: biome ci . --linter-enabled=false

  lint-biome:
    name: Lint (Biome)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: latest

      - name: Run Biome
        run: biome ci . || true
